// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_application_1/test/services/location_sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_application_1/models/cuestionario.dart' as _i8;
import 'package:flutter_application_1/models/location_point.dart' as _i3;
import 'package:flutter_application_1/models/pending_location.dart' as _i10;
import 'package:flutter_application_1/models/user_profile.dart' as _i2;
import 'package:flutter_application_1/models/visit_plan.dart' as _i4;
import 'package:flutter_application_1/services/api_service.dart' as _i6;
import 'package:flutter_application_1/services/pending_location_store.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHorarioOption_0 extends _i1.SmartFake implements _i2.HorarioOption {
  _FakeHorarioOption_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationHistory_2 extends _i1.SmartFake
    implements _i3.LocationHistory {
  _FakeLocationHistory_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVisitPlan_3 extends _i1.SmartFake implements _i4.VisitPlan {
  _FakeVisitPlan_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVisitItem_4 extends _i1.SmartFake implements _i4.VisitItem {
  _FakeVisitItem_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_5 extends _i1.SmartFake implements _i5.Database {
  _FakeDatabase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserProfile?> fetchUserProfile(
    String? saaSubject, {
    bool? forceNetwork = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchUserProfile,
              [saaSubject],
              {#forceNetwork: forceNetwork},
            ),
            returnValue: _i7.Future<_i2.UserProfile?>.value(),
          )
          as _i7.Future<_i2.UserProfile?>);

  @override
  _i7.Future<List<_i2.EquipoOption>> fetchEquiposActivos() =>
      (super.noSuchMethod(
            Invocation.method(#fetchEquiposActivos, []),
            returnValue: _i7.Future<List<_i2.EquipoOption>>.value(
              <_i2.EquipoOption>[],
            ),
          )
          as _i7.Future<List<_i2.EquipoOption>>);

  @override
  _i7.Future<List<_i2.HorarioOption>> fetchHorarios() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHorarios, []),
            returnValue: _i7.Future<List<_i2.HorarioOption>>.value(
              <_i2.HorarioOption>[],
            ),
          )
          as _i7.Future<List<_i2.HorarioOption>>);

  @override
  _i7.Future<_i8.Cuestionario?> fetchCuestionarioActivo() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCuestionarioActivo, []),
            returnValue: _i7.Future<_i8.Cuestionario?>.value(),
          )
          as _i7.Future<_i8.Cuestionario?>);

  @override
  _i7.Future<List<_i8.Pregunta>> fetchPreguntasPorCuestionario(
    int? idCuestionario,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPreguntasPorCuestionario, [idCuestionario]),
            returnValue: _i7.Future<List<_i8.Pregunta>>.value(<_i8.Pregunta>[]),
          )
          as _i7.Future<List<_i8.Pregunta>>);

  @override
  _i7.Future<void> registrarRespuestas(
    List<_i8.RespuestaPayload>? respuestas,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registrarRespuestas, [respuestas]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.RespuestaPregunta>> fetchRespuestasCuestionario({
    required int? idCuestionario,
    required int? idPersona,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRespuestasCuestionario, [], {
              #idCuestionario: idCuestionario,
              #idPersona: idPersona,
            }),
            returnValue: _i7.Future<List<_i8.RespuestaPregunta>>.value(
              <_i8.RespuestaPregunta>[],
            ),
          )
          as _i7.Future<List<_i8.RespuestaPregunta>>);

  @override
  _i7.Future<List<_i8.RespuestaPregunta>> fetchRespuestasPorItem({
    required int? idItem,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRespuestasPorItem, [], {#idItem: idItem}),
            returnValue: _i7.Future<List<_i8.RespuestaPregunta>>.value(
              <_i8.RespuestaPregunta>[],
            ),
          )
          as _i7.Future<List<_i8.RespuestaPregunta>>);

  @override
  _i7.Future<void> sendMetric({
    required String? action,
    required String? screen,
    String? status = 'success',
    int? durationMs,
    String? version,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMetric, [], {
              #action: action,
              #screen: screen,
              #status: status,
              #durationMs: durationMs,
              #version: version,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.HorarioOption> fetchHorarioById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHorarioById, [id]),
            returnValue: _i7.Future<_i2.HorarioOption>.value(
              _FakeHorarioOption_0(
                this,
                Invocation.method(#fetchHorarioById, [id]),
              ),
            ),
          )
          as _i7.Future<_i2.HorarioOption>);

  @override
  _i7.Future<_i2.UserProfile> saveUserProfile({
    int? id,
    required String? saaSubject,
    required String? usuario,
    required String? nombre,
    required int? estado,
    required int? horarioId,
    required int? equipoId,
    String? email,
    required String? usuarioSesion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [], {
              #id: id,
              #saaSubject: saaSubject,
              #usuario: usuario,
              #nombre: nombre,
              #estado: estado,
              #horarioId: horarioId,
              #equipoId: equipoId,
              #email: email,
              #usuarioSesion: usuarioSesion,
            }),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_1(
                this,
                Invocation.method(#saveUserProfile, [], {
                  #id: id,
                  #saaSubject: saaSubject,
                  #usuario: usuario,
                  #nombre: nombre,
                  #estado: estado,
                  #horarioId: horarioId,
                  #equipoId: equipoId,
                  #email: email,
                  #usuarioSesion: usuarioSesion,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<void> sendLocation({
    required String? firebaseUid,
    required _i3.LocationPoint? point,
    int? batteryLevel,
    String? activityType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendLocation, [], {
              #firebaseUid: firebaseUid,
              #point: point,
              #batteryLevel: batteryLevel,
              #activityType: activityType,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendLocationBatch(List<Map<String, dynamic>>? locations) =>
      (super.noSuchMethod(
            Invocation.method(#sendLocationBatch, [locations]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<double> fetchDailyDistance({
    required String? firebaseUid,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDailyDistance, [], {
              #firebaseUid: firebaseUid,
              #date: date,
            }),
            returnValue: _i7.Future<double>.value(0.0),
          )
          as _i7.Future<double>);

  @override
  _i7.Future<_i3.LocationHistory> fetchLocationHistory({
    required String? firebaseUid,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLocationHistory, [], {
              #firebaseUid: firebaseUid,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i7.Future<_i3.LocationHistory>.value(
              _FakeLocationHistory_2(
                this,
                Invocation.method(#fetchLocationHistory, [], {
                  #firebaseUid: firebaseUid,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LocationHistory>);

  @override
  _i7.Future<_i3.LocationHistory> fetchHistory({
    required String? firebaseUid,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHistory, [], {
              #firebaseUid: firebaseUid,
              #start: start,
              #end: end,
            }),
            returnValue: _i7.Future<_i3.LocationHistory>.value(
              _FakeLocationHistory_2(
                this,
                Invocation.method(#fetchHistory, [], {
                  #firebaseUid: firebaseUid,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LocationHistory>);

  @override
  _i7.Future<_i4.VisitPlan> fetchVisitPlanForMe() =>
      (super.noSuchMethod(
            Invocation.method(#fetchVisitPlanForMe, []),
            returnValue: _i7.Future<_i4.VisitPlan>.value(
              _FakeVisitPlan_3(
                this,
                Invocation.method(#fetchVisitPlanForMe, []),
              ),
            ),
          )
          as _i7.Future<_i4.VisitPlan>);

  @override
  _i7.Future<_i4.VisitPlan> reorderVisitItems({
    required int? planId,
    required List<int>? itemIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderVisitItems, [], {
              #planId: planId,
              #itemIds: itemIds,
            }),
            returnValue: _i7.Future<_i4.VisitPlan>.value(
              _FakeVisitPlan_3(
                this,
                Invocation.method(#reorderVisitItems, [], {
                  #planId: planId,
                  #itemIds: itemIds,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.VisitPlan>);

  /*@override
  _i7.Future<_i4.VisitItem> updateVisitState({
    required int? itemId,
    required _i4.VisitItemState? newState,
    double? startLatitude,
    double? startLongitude,
    double? eventLatitude,
    double? eventLongitude,
    required String? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisitState, [], {
              #itemId: itemId,
              #newState: newState,
              #startLatitude: startLatitude,
              #startLongitude: startLongitude,
              #eventLatitude: eventLatitude,
              #eventLongitude: eventLongitude,
              #source: source,
            }),
            returnValue: _i7.Future<_i4.VisitItem>.value(
              _FakeVisitItem_4(
                this,
                Invocation.method(#updateVisitState, [], {
                  #itemId: itemId,
                  #newState: newState,
                  #startLatitude: startLatitude,
                  #startLongitude: startLongitude,
                  #eventLatitude: eventLatitude,
                  #eventLongitude: eventLongitude,
                  #source: source,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.VisitItem>);*/

  @override
  _i7.Future<bool> checkBackendAvailable({
    Duration? timeout = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkBackendAvailable, [], {#timeout: timeout}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  /*@override
  _i7.Future<_i4.VisitItem> completeVisit({
    required int? itemId,
    bool? complex,
    bool? foundProblem,
    String? problemNote,
    String? otherInfo,
    double? eventLatitude,
    double? eventLongitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeVisit, [], {
              #itemId: itemId,
              #complex: complex,
              #foundProblem: foundProblem,
              #problemNote: problemNote,
              #otherInfo: otherInfo,
              #eventLatitude: eventLatitude,
              #eventLongitude: eventLongitude,
            }),
            returnValue: _i7.Future<_i4.VisitItem>.value(
              _FakeVisitItem_4(
                this,
                Invocation.method(#completeVisit, [], {
                  #itemId: itemId,
                  #complex: complex,
                  #foundProblem: foundProblem,
                  #problemNote: problemNote,
                  #otherInfo: otherInfo,
                  #eventLatitude: eventLatitude,
                  #eventLongitude: eventLongitude,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.VisitItem>);*/

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PendingLocationStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPendingLocationStore extends _i1.Mock
    implements _i9.PendingLocationStore {
  MockPendingLocationStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i5.Database>.value(
              _FakeDatabase_5(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i5.Database>);

  @override
  _i7.Future<int> insert(_i10.PendingLocation? location) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [location]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i10.PendingLocation>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i7.Future<List<_i10.PendingLocation>>.value(
              <_i10.PendingLocation>[],
            ),
          )
          as _i7.Future<List<_i10.PendingLocation>>);

  @override
  _i7.Future<List<_i10.PendingLocation>> getBatchForSubject(
    String? saaSubject,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchForSubject, [saaSubject, limit]),
            returnValue: _i7.Future<List<_i10.PendingLocation>>.value(
              <_i10.PendingLocation>[],
            ),
          )
          as _i7.Future<List<_i10.PendingLocation>>);

  @override
  _i7.Future<List<_i10.PendingLocation>> getAllForSubject(String? saaSubject) =>
      (super.noSuchMethod(
            Invocation.method(#getAllForSubject, [saaSubject]),
            returnValue: _i7.Future<List<_i10.PendingLocation>>.value(
              <_i10.PendingLocation>[],
            ),
          )
          as _i7.Future<List<_i10.PendingLocation>>);

  @override
  _i7.Future<List<_i10.PendingLocation>> getBatch(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getBatch, [limit]),
            returnValue: _i7.Future<List<_i10.PendingLocation>>.value(
              <_i10.PendingLocation>[],
            ),
          )
          as _i7.Future<List<_i10.PendingLocation>>);

  @override
  _i7.Future<int> deleteBatch(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBatch, [ids]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> countForSubject(String? saaSubject) =>
      (super.noSuchMethod(
            Invocation.method(#countForSubject, [saaSubject]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> purgeForSubject(
    String? saaSubject, {
    required Duration? maxAge,
    required int? maxRows,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #purgeForSubject,
              [saaSubject],
              {#maxAge: maxAge, #maxRows: maxRows},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<(String, String)?> getMinMaxTimestampsForSubject(
    String? saaSubject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMinMaxTimestampsForSubject, [saaSubject]),
            returnValue: _i7.Future<(String, String)?>.value(),
          )
          as _i7.Future<(String, String)?>);

  @override
  _i7.Future<String?> peekOldest() =>
      (super.noSuchMethod(
            Invocation.method(#peekOldest, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);
}
